/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common";
import type { Name, NameInterface } from "../Name";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea26469706673582212205fa0b1a641b28079e99a4f2d99b19df27857d7ec22f25b613592c8f549d7d88964736f6c63430008090033";

type NameConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: NameConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Name__factory extends ContractFactory {
  constructor(...args: NameConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Name> {
    return super.deploy(overrides || {}) as Promise<Name>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Name {
    return super.attach(address) as Name;
  }
  override connect(signer: Signer): Name__factory {
    return super.connect(signer) as Name__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): NameInterface {
    return new utils.Interface(_abi) as NameInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Name {
    return new Contract(address, _abi, signerOrProvider) as Name;
  }
}
